### PR TITLE
clarify secp256k1 pubkey format

### PR DESCRIPTION
**Pull request by jleni**
Make explicit that uncompressed pubkeys must be used to generate addresses. 
Incorrectly using a compressed pubkey (33 bytes) can result in loss of funds as a different address will be generated and the corresponding pub/sec keys will not be accessible.

### CODE REVIEW

**Comment by jleni** [comment]
any updates on this?

**Comment by whyrusleeping** [comment]
@Kubuxu can you confirm that this is correct?

**Comment by jleni** [comment]
yes, my suggestion is to make this explicit. 

If anyone in the community does this incorrectly (because is unclear), for a given private key if funds sent to `pubkey (compressed) => address`, they will be lost.

The other option is to add a workaround in the verification code that checks a match between the source address and the recovered pubkey in both compressed and uncompressed forms. 

Still, for now I would start by clarifying the current expectation in the specs.

**Comment by Kubuxu** [comment]
Can you rebase the PR, thanks.

**Pull request merged**
