### PR TITLE
NSE calculation

### PR DESCRIPTION
**Pull request by nicola**
To run:

```
$ ./orient/bin/orient web --system=src/orient/nse.orient --port=8000
$ obs serve 8081 src/orient/viz
```

### CODE REVIEW

**Comment by nicola** [comment]
This PR is ready to merge on my end.

**Comment by nicola** [comment]
Well ubercalc stopped working after my rebase :/

**Comment by sternhenri** [comment]
Have a reviewer who should look at this @nicola ?

**Comment by nicola** [comment]
It could be @porcuquine or @irenegia maybe?

**Comment by nicola** [comment]
We should just merge it in, this does not have any impact on the spec.

**Comment by nicola** [comment]
yes we should merge it! I still use this code every now and then. It's the go to resource for NSE uber-calc

**Comment by hugomrdias** [comment]
this is old stuff @yiannisbot it uses orient

**Comment by nicola** [comment]
It's ok to make a new repo for these models

**Comment by ianconsolata** [comment]
This is more than 3 years old now -- is this PR still relevant, or can I close it?

**Comment by vmx** [comment]
I'll close this one as NSE never hit mainnet and the code is preserved in this PR, it doesn't need to be on the main branch. In case anyone disagrees, feel free to re-open.

**Pull request closed without merging**
