### PR TITLE
miner should validate commP

### PR DESCRIPTION
**Pull request by acruikshank**
### Problem

A malicious client can create a deal proposal containing payment information with a bogus commP. If the miner waits until the sector is sealed to check commP, the client can cancel payments and still have the miner store their data.

### Solution

Miners should confirm that the `commP` supplied in payment conditions is correct as soon as they receive the piece data.

### CODE REVIEW

**Comment by pooja** [comment]
[miner should validate commP](https://trello.com/c/BDiEqTVm/19-miner-should-validate-commp)

**Comment by sternhenri** [comment]
Thanks for this @acruikshank! I believe this PR's need is patched by deals-on-chain and the new storage market work done by @hannahhoward. Can you confirm @acruikshank and close this PR accordingly please?

**Comment by mishmosh** [comment]
Thank you for this @acruikshank and sorry for the loooong delay. I believe this is now superseded by https://filecoin-project.github.io/specs/#systems__filecoin_markets__storage_market. Can you check & close if so?

**Comment by acruikshank** [comment]
This check appears to have landed in the spec. Closing this issue.

**Pull request closed without merging**
