### PR TITLE
feat(content): adds poseidon spec

### PR DESCRIPTION
**Pull request by DrPeterVanNostrand**
Adds spec for the Poseidon hash function to the crypto primitives section.

### CODE REVIEW

**Comment by porcuquine** [comment]
Is there a way to see a preview of how this will be rendered?

**Comment by DrPeterVanNostrand** [comment]
There is a HackMD doc [here](https://hackmd.io/XRSBzLeXRmqtETruBaEGuQ?view) which should be similar. I was under the impression that PR'ing into the `beta` branch (beta.spec.filecoin.io) was basically used to check rendering.

**Review by porcuquine — APPROVED** [review]
I accidentally reviewed this content in the `neptune` repo instead of here. Please see my minor comments there instead: https://github.com/filecoin-project/neptune/pull/84#pullrequestreview-610223427

**Comment by vmx** [comment]
@DrPeterVanNostrand the `master` branch is now the real thing (`beta` was just a temporary thing, it isn't a branch where things go first before they are merged into master), so you should PR against `master`.

**Comment by DrPeterVanNostrand** [comment]
@vmx oh ok, thanks!

**Review by porcuquine — APPROVED** [review]
It's a bit hard to finalize reviews because of a near deadlock and without an easy preview. However, assuming the content here now corresponds to what I reviewed in the neptune repo (https://github.com/filecoin-project/neptune/pull/88) and that all relevant changes have been ported here, then I approve. Once this is merged, we can finalize the neptune changes as well.

**Comment by porcuquine** [comment]
I do note that CI is failing here, and that might need to be addressed before merging. I have no comment on procedure though, since I don't know the current state or practice in this repo.

**Comment by DrPeterVanNostrand** [comment]
@porcuquine this PR can be reviewed now, it is rendered here: https://bafybeifozsgpiavj5c734likfqcplt3nymsutcsuzoeyqi5z5dujzvptoe.on.fleek.co/#section-algorithms.crypto.poseidon

**Review by porcuquine — APPROVED** [review]
Looks good  to me. Well done.

**Pull request merged**
