### PR TITLE
Domain Separation Tags

### PR DESCRIPTION
**Pull request by nikkolasg**
HS Edit:

follow up to https://github.com/filecoin-project/specs/pull/642

====
This PR adds a Domain Separation Tag for each of the following computation and the verification counter part:
- Ticket generation
- Election Proof 
- Block Signing

*Note 1*: I tried to put it all relevant places, sometimes it added it twice for generating a ticket for example; I am not sure if the redundancy is necessary or not but I put it everywhere.
*Note 2*: Sometimes it is in commented form, but I still added the tag (see BLOCK for example)

### CODE REVIEW

**Comment by anorth** [comment]
FYI @ZenGround0 @acruikshank changes to block and ticket signatures.

**Comment by jbenet** [comment]
I think this needs to be rebased on top of master, as @sternhenri's PR landed

**Comment by sternhenri** [comment]
on it. wanted to fix it anyhow but was waiting for my PR to land

**Comment by sternhenri** [comment]
closing in favor of https://github.com/filecoin-project/specs/pull/677

**Pull request closed without merging**
