### PR TITLE
correct mining cycle graph

### PR DESCRIPTION
**Pull request by sternhenri**
Fixing mining cycle to place cutoff after epoch boundary, and adding a slightly more succinct algorithm.

### CODE REVIEW

**Comment by anorth** [comment]
I don't think the diagram matches the words. The orange Rx seems wrong since a node won't accept a block that arrives before the epoch starts. the orange should match the green exactly (and so is redundant).

**Comment by sternhenri** [comment]
You're right. I'll fix it. I'm not sure why we force quantization of the timestamps? Ie why is a block with a non-quantized (but otherwise correct) timestamp invalid?

**Comment by anorth** [comment]
Timestamps are redundant, a pure function of epoch. IMO we should remove
them. The spec is out of date here.

https://github.com/filecoin-project/specs/issues/904

**Comment by sternhenri** [comment]
I'll address in your comment.

**Comment by whyrusleeping** [comment]
(my approval was on commit 9f033cc)

**Pull request merged**
