### PR TITLE
added grace period and call out to network time

### PR DESCRIPTION
**Pull request by sternhenri**
Addresses https://github.com/filecoin-project/specs/issues/308. I'm holding off on the adjustable block-time idea from @whyrusleeping for now given I am not sure yet whether it doesn't cause a problem whereas attackers who can break the VDF can effectively prevent anyone else from mining by forcing the network to adopt their effective block-time (which is what the block delay sought to solve in the first place).

- Also chose to add some explicit mention of network time protocols to not have people just default to machine time.

### CODE REVIEW

**Comment by dignifiedquire** [comment]
Missing an actual value for the drift

**Comment by sternhenri** [comment]
I'd recommend a default on the order of 12*conf time or in FIL's case, 6 minutes... (BTC likewise uses 2 hours).

Though that's an impl choice imo

**Comment by dignifiedquire** [comment]
@whyrusleeping please merge if this looks good to you

**Comment by whyrusleeping** [comment]
@sternhenri i think that values > 1 block time are too much. In bitcoin, its okay if one blocks timestamp is before its parents. we are not okay with that.

allowing large drifts like this means that an attacker can 'rush', releasing many blocks at the same time with the bare minimum difference in timestamps, up to the drift limit. Granted, they have to be able to mine those blocks anyways, but it seems rather adversarial

**Comment by sternhenri** [comment]
Why is it more ok with Bitcoin? Your point is well taken though and perhaps we should scale back to ~20 secs. Or 2/3 blocktime. It’s slightly on the short end for me given network prop times (ie 90th percentile slowness in btc gossip is closer to 40secs) but the downside is not awful... and easy to adjust for testnet. 

That said, we do have other means of limiting rushing, so to me this is more about relaxing clock times while limiting the potential this creates.

**Comment by whyrusleeping** [comment]
Bitcoin doesnt care about the same sort of attacks we do. If you can generate bitcoin blocks faster than 10 minutes, you absolutely should do that, and the system wants you to.

> (ie 90th percentile slowness in btc gossip is closer to 40secs)

Thats for bitcoin, Ethereum is much less, its all a function of block size.

2/3 blocktime SGTM for now, we're assuming that all miners have fairly synchronized clocks (as ethereum does), and thats a pretty acceptable range.

**Comment by sternhenri** [comment]
fair enough, changed reco. Your point is well taken, though I'd nuance it in that if you can generate in less than 10 mins, they can't stop you, but they'll update the difficulty.

I see this as more of a drawback of our VRC, just as with BTC this is also meant to mitigate potential rushing, however maybe our source of timing constraint (VDF vs hashing) is by nature a bit different...

**Pull request merged**
