### PR TITLE
fix: sigma prime changes

### PR DESCRIPTION
**Pull request by DrPeterVanNostrand**
This PR contains the spec changes that were requested by Sigma Prime during their proofs audit.

### CODE REVIEW

**Comment by DrPeterVanNostrand** [comment]
@vmx I would prefer to leave this PR as only the changes requested by sigma prime and leave spelling mistakes, which I'm sure there are many of, to a separate pr.

**Comment by vmx** [comment]
@hugomrdias please merge, to me you're kind of the gatekeeper here and i don't want to destroy anything :)

**Comment by cryptonemo** [comment]
@hugomrdias Thanks!  I'm tracking this and wanted to know if you know the final IPFS link for after the merge (for sharing with external parties).

**Comment by hugomrdias** [comment]
Just look for this commit you want and click the green check on the left.


For this one its https://bafybeig5jbnrabcmyboisv2luzns6fpsm3mjrvucdk725bmvji3ilz72we.ipfs.dweb.link/

**Comment by vmx** [comment]
@cryptonemo I'd rather use https://bafybeidxw5vxjdwsun2zc2illagf43v6w5r5w63vg455h7vjesbyqssg64.ipfs.dweb.link/ (which is the commit on the branch and not the PR).

**Comment by cryptonemo** [comment]
Ok, thanks guys.  @hugomrdias I had that one previously, but wanted the latest.  I believe @vmx provided what I need

**Pull request merged**
