### PR TITLE
Proofs impl hs

### PR DESCRIPTION
**Pull request by sternhenri**
fixed randomness issues created by me.

### CODE REVIEW

**Comment by sternhenri** [comment]
Fishy change to me may be the change in `orient` which i may have reverted (I've not touched orient)

**Comment by porcuquine** [comment]
The thing to be aware of is that `orient` is a submodule, so if it gets updated somewhere and you don't `git submodule update` to get the latest, then you're likely to accidentally recommit the old version. I don't know what happened here and don't have time to dig in now, but that's just a general PSA. If you see a change to `orient` in your own commits, and you didn't make it intentionally (generally because you've intentionally pulled in the latest `orient/master`), you've likely done this.

**Comment by sternhenri** [comment]
super useful! I've been carrying around an old orient that I've avoided committing forever. Thanks

**Comment by sternhenri** [comment]
Assuming this is now stale @porcuquine

**Pull request closed without merging**
